server:
  port: 8080
springdoc:
  swagger-ui:
    path: /api/swagger-ui
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/btvn_security?serverTimezone=UTC
    username: root
    password: root
  data:
    cassandra:
      schema-action: create_if_not_exists
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret_key: vitSecretKey
  time_expiration: 86400000

mail:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

